#!/bin/bash 
FROM ubuntu:16.04
MAINTAINER shlee <lshyeung@gmail.com>

RUN apt-get update
RUN apt-get install git -y

RUN git clone https://github.com/stevelee91/ml_pattern /tmp/ml_pattern

RUN apt-get install -y python3
RUN apt-get install -y python3-pip python-dev build-essential -y
RUN apt-get install -y curl 
RUN pip3 install numpy
RUN pip3 install keras
RUN pip3 install tensorflow


CMD ["/usr/bin/python3", "/tmp/ml_pattern/keras_mnist.py"]

