---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ml-pattern
  name: ml-pattern
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 31114
  selector:
    app: ml-pattern
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pattern
spec:
  selector:
    matchLabels:
      app: ml-pattern    
  template:
    metadata:
      labels:
        app: ml-pattern
    spec:
      containers:
      - name: ml-pattern
        image: lshyeung/keras_pattern2
        ports:
        - containerPort: 8080

