---
apiVersion: v1
kind: Service
metadata:
  name: api-server
  labels:
    app: api-server
spec:
  type: NodePort
  ports:
  - name: "api-server"
    port: 5000
    nodePort: 32014
  selector:
    app: api-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
spec:
  selector:
    matchLabels:
      app: api-server       
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
      - name: api-server
        image: lshyeung/api_server_pattern
        ports:
        - containerPort: 5000

