---
apiVersion: v1
kind: Service
metadata:
  name: cpu-load
  labels:
    app: cpu-load
spec:
  type: NodePort
  ports:
  - name: "cpu-load"
    port: 5800
    nodePort: 32113
  selector:
    app: cpu-load
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-load
spec:
  selector:
    matchLabels:
      app: cpu-load
  template:
    metadata:
      labels:
        app: cpu-load
    spec:
      containers:
      - name: cpu-load
        image: lshyeung/cpu-load
        ports:
        - containerPort: 5800
