---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-1
  labels:
    app: kafka-broker
spec:
  ports:
  - name: "kafka"
    port: 9092
  selector:
    app: kafka-broker
    brokerID: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker-1
spec:
  selector:
    matchLabels:
      app: kafka-broker
      brokerID: "1"
  template:
    metadata:
      labels:
        app: kafka-broker
        brokerID: "1"
    spec:
      containers:
      - name: kafka-broker
        image: wurstmeister/kafka:latest
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "kafka-broker-1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "kafka-zookeeper:2181"
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_CREATE_TOPICS
          value: "Device1:1:1"
        - name: KAFKA_CREATE_TOPICS
          value: "Device2:1:1"
        - name: KAFKA_CREATE_TOPICS
          value: "Device3:1:1"
        - name: KAFKA_CREATE_TOPICS
          value: "Device4:1:1"
        - name: KAFKA_CREATE_TOPICS
          value: "Device5:1:1"
        - name: KAFKA_CREATE_TOPICS
          value: "Device6:1:1"
        - name: KAFKA_CREATE_TOPICS
          value: "Device7:1:1"
        - name: KAFKA_CREATE_TOPICS
          value: "Device8:1:1"
        - name: KAFKA_CREATE_TOPICS
          value: "Device9:1:1"
        - name: KAFKA_CREATE_TOPICS
          value: "Device10:1:1"
        - name: KAFKA_CREATE_TOPICS
          value: "Device11:1:1"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-2
  labels:
    app: kafka-broker
spec:
  ports:
  - name: "kafka"
    port: 9092
  selector:
    app: kafka-broker
    brokerID: "2"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker-2
spec:
  selector:
    matchLabels:
      app: kafka-broker
      brokerID: "2"        
  template:
    metadata:
      labels:
        app: kafka-broker
        brokerID: "2"
    spec:
      containers:
      - name: kafka-broker
        image: wurstmeister/kafka:latest
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "kafka-broker-2"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "kafka-zookeeper:2181"
        - name: KAFKA_BROKER_ID
          value: "2"
        - name: KAFKA_CREATE_TOPICS
          value: "Device1:1:1"
        - name: KAFKA_CREATE_TOPICS
          value: "Device2:1:1"
        - name: KAFKA_CREATE_TOPICS
          value: "Device3:1:1"
        - name: KAFKA_CREATE_TOPICS
          value: "Device4:1:1"
        - name: KAFKA_CREATE_TOPICS
          value: "Device5:1:1"
        - name: KAFKA_CREATE_TOPICS
          value: "Device6:1:1"
        - name: KAFKA_CREATE_TOPICS
          value: "Device7:1:1"
        - name: KAFKA_CREATE_TOPICS
          value: "Device8:1:1"
        - name: KAFKA_CREATE_TOPICS
          value: "Device9:1:1"
        - name: KAFKA_CREATE_TOPICS
          value: "Device10:1:1"
        - name: KAFKA_CREATE_TOPICS
          value: "Device11:1:1"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-3
  labels:
    app: kafka-broker
spec:
  ports:
  - name: "kafka"
    port: 9092
  selector:
    app: kafka-broker
    brokerID: "3"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker-3
spec:
  selector:
    matchLabels:
      app: kafka-broker
      brokerID: "3"
  template:
    metadata:
      labels:
        app: kafka-broker
        brokerID: "3"
    spec:
      containers:
      - name: kafka-broker
        image: wurstmeister/kafka:latest
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "kafka-broker-3"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "kafka-zookeeper:2181"
        - name: KAFKA_BROKER_ID
          value: "3"
        - name: KAFKA_CREATE_TOPICS
          value: "Device1:1:1"
        - name: KAFKA_CREATE_TOPICS
          value: "Device2:1:1"
        - name: KAFKA_CREATE_TOPICS
          value: "Device3:1:1"
        - name: KAFKA_CREATE_TOPICS
          value: "Device4:1:1"
        - name: KAFKA_CREATE_TOPICS
          value: "Device5:1:1"
        - name: KAFKA_CREATE_TOPICS
          value: "Device6:1:1"
        - name: KAFKA_CREATE_TOPICS
          value: "Device7:1:1"
        - name: KAFKA_CREATE_TOPICS
          value: "Device8:1:1"
        - name: KAFKA_CREATE_TOPICS
          value: "Device9:1:1"
        - name: KAFKA_CREATE_TOPICS
          value: "Device10:1:1"
        - name: KAFKA_CREATE_TOPICS
          value: "Device11:1:1"

