---
apiVersion: v1
kind: Service
metadata:
  name: kafka-zookeeper
  labels:
    app: kafka-zookeeper
spec:
  ports:
  - name: "zookeeper"
    port: 2181
  selector:
    app: kafka-zookeeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-zookeeper
spec:
  selector:
    matchLabels:
      app: kafka-zookeeper
  template:
    metadata:
      labels:
        app: kafka-zookeeper
    spec:
      containers:
      - name: kafka-zookeeper
        image: wurstmeister/zookeeper:latest
        ports:
        - containerPort: 2181
