#!/bin/bash 
FROM ubuntu:16.04
MAINTAINER shlee <lshyeung@gmail.com>

RUN apt-get update
RUN apt-get install git -y

RUN git clone https://github.com/SmartX-Team/Smart-Energy-Service /tmp/Smart-Energy-Service

RUN apt-get install -y libcurl3 openssl curl
RUN apt-get install -y python2.7 python-pip
RUN apt-get install -y python3-pip
RUN pip install requests
RUN pip install pymongo
RUN pip install flask
RUN pip install kafka-python
RUN pip install queuelib
RUN pip install influxdb
RUN pip install pandas
RUN pip install msgpack
RUN pip install pyowm

CMD ["/usr/bin/python", "/tmp/Smart-Energy-Service/consumer/consumer_Weather.py"]

